### ISSUE TITLE
Warn about invalid insertions

### ISSUE THREAD

**Issue by johankool** [PicnicSupermarket/localicious#16]
`This is a {{s}} test` fails, because it should have been `This is a %1{{s}} test`. It would be nice if the validation step checks for this mistake.

**Comment by larslockefeer** [comment]
Nice idea!

An alternative approach could be to add the `%1, %2` etc. when they are not provided, based on the order of the placeholders in the string. So `This is a {{s}} test` would simply become `This is a %1{{s}} test` during the `render` phase.

I'm not sure yet what's best. When a string contains multiple, placeholders of the same type, I lean towards your proposal because it is good to be explicit about the ambiguity. But when a string contains only a single placeholder or multiple placeholders of different types, it would be nice that it "just works".

@LcTwisk any thoughts/opinions on this?

**Comment by LcTwisk** [comment]
Good question!
I think we should just have 1 single way to do it, and therefore throw an error if the `%1` is missing. Accepting two different formats can become confusing pretty fast.
